### ISSUE TITLE
Show collection's available cards

### ISSUE THREAD

**Issue by Dazorn96** [keldaanInteractive/pokemonAutoChess#327]
Hi,
I am a bit confused while surfing over the **Collection** tab.

I think it would be easier to understand which cards you have just **coloring the pokémon sprite**, like the example below (Cleffa and Poochyena):

![image](https://user-images.githubusercontent.com/10536581/214353810-88258729-68fe-4430-8d7c-79d89c162356.png)

**Comment by sylvainpolletvillard** [comment]
I was thinking of that too, also possibly reduce the brightness of grayscale sprites

**Comment by keldaan-ag** [comment]
https://github.com/keldaanInteractive/pokemonAutoChess/commit/27fa8b575c4b5e66050eaf8fdf041eb4117c1d27
